# FIFA 19 Project

## Importing the Libraries


In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix , accuracy_score,r2_score

##Import the Dataset

In [50]:
dataset = pd.read_csv("FIFA19_player_stats.csv")
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

In [51]:
x

array([[3.0, 68.0, 64.0, ..., 11.0, 11.0, 'RCM'],
       [4.0, 77.0, 70.0, ..., 13.0, 7.0, 'LF'],
       [4.0, 80.0, 68.0, ..., 14.0, 8.0, 'CM'],
       ...,
       [2.0, 39.0, 29.0, ..., 14.0, 7.0, 'CB'],
       [3.0, 58.0, 55.0, ..., 10.0, 7.0, 'CAM'],
       [2.0, 22.0, 22.0, ..., 15.0, 10.0, 'CB']], dtype=object)

In [52]:
y

array([71, 86, 79, ..., 58, 62, 51])

##Encoding Independent Variable

In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder() , [-1])] ,remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

In [54]:
x

array([[0.0, 0.0, 0.0, ..., 13.0, 11.0, 11.0],
       [0.0, 0.0, 0.0, ..., 6.0, 13.0, 7.0],
       [0.0, 0.0, 0.0, ..., 7.0, 14.0, 8.0],
       ...,
       [0.0, 1.0, 0.0, ..., 9.0, 14.0, 7.0],
       [1.0, 0.0, 0.0, ..., 11.0, 10.0, 7.0],
       [0.0, 1.0, 0.0, ..., 11.0, 15.0, 10.0]], dtype=object)

##Dealing with missing values

In [55]:
#If missing value is present returns true or else false
from sklearn.impute import MissingIndicator
indicator = MissingIndicator()
indicator.fit_transform(x)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [56]:
from sklearn.impute import SimpleImputer
imp_x = SimpleImputer(missing_values=np.nan, strategy='mean')
x = imp_x.fit_transform(x)
imp_y = SimpleImputer(missing_values=np.nan, strategy='mean')
y = imp_x.fit_transform(y.reshape(-1,1))

In [57]:
x

array([[ 0.,  0.,  0., ..., 13., 11., 11.],
       [ 0.,  0.,  0., ...,  6., 13.,  7.],
       [ 0.,  0.,  0., ...,  7., 14.,  8.],
       ...,
       [ 0.,  1.,  0., ...,  9., 14.,  7.],
       [ 1.,  0.,  0., ..., 11., 10.,  7.],
       [ 0.,  1.,  0., ..., 11., 15., 10.]])

In [58]:
y

array([[71.],
       [86.],
       [79.],
       ...,
       [58.],
       [62.],
       [51.]])

##Feature Scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)
sc_y = StandardScaler()
y = sc_y.fit_transform(y)

##Spilting the Data into Training  and Test set

In [60]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [61]:
x_train

array([[-0.24, -0.33, -0.23, ..., -0.44, -0.26, -0.54],
       [-0.24, -0.33, -0.23, ..., -0.2 , -0.38, -0.15],
       [-0.24, -0.33, -0.23, ..., -0.56, -0.14, -0.04],
       ...,
       [-0.24, -0.33, -0.23, ...,  2.53,  2.56,  3.08],
       [-0.24, -0.33, -0.23, ..., -0.14, -0.43, -0.1 ],
       [-0.24, -0.33, -0.23, ..., -0.5 , -0.43, -0.43]])

In [62]:
x_test

array([[-0.24, -0.33, -0.23, ..., -0.32, -0.49, -0.43],
       [-0.24,  3.04, -0.23, ..., -0.44, -0.49, -0.6 ],
       [ 4.24, -0.33, -0.23, ..., -0.26, -0.26,  0.13],
       ...,
       [-0.24,  3.04, -0.23, ..., -0.62, -0.08, -0.32],
       [-0.24, -0.33, -0.23, ..., -0.56, -0.08, -0.37],
       [-0.24, -0.33, -0.23, ..., -0.38, -0.67, -0.6 ]])

In [63]:
y_train

array([[-2.21],
       [-0.61],
       [ 0.83],
       ...,
       [-0.18],
       [ 0.83],
       [-0.18]])

In [64]:
y_test

array([[-0.76],
       [-1.19],
       [-0.03],
       ...,
       [-0.18],
       [-1.19],
       [-1.77]])

###SVR

In [65]:
from sklearn.svm import SVR
sv_reg = SVR(kernel = 'rbf')
sv_reg.fit(x_train , y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [71]:
y_pred_svr = (sv_reg.predict(x_test))

array([[-0.79, -0.76],
       [-1.2 , -1.19],
       [ 0.  , -0.03],
       ...,
       [-0.15, -0.18],
       [-1.2 , -1.19],
       [-1.72, -1.77]])

In [72]:
r2_score(y_test,y_pred_svr)

0.9860623727149038